spring.application.name=backendd


# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.database=legalyze_db
spring.data.mongodb.uri=mongodb://localhost:27017/legalyze_db


# JWT Secret Key (placeholder, will add in security later)

jwt.secret=MySuperSecretKeyForLegalyze123
jwt.expiration=86400000   # 1 day in ms

#spring.security.enabled=false
#spring.security.basic.enabled=false